
const companyExclusions = [
  /Apex Systems/,
  /Braintrust/,
  /Capgemini/,
  /Clera/,
  /Cognizant/,
  /Compunnel/,
  /GlobalLogic/,
  /HCLTech/,
  /Infojini/,
  /Infosys/,
  /Jobs via Dice/,
  /Motion Recruitment/,
  /Net2Source/,
  /NTT DATA/,
  /^Pyramid\b/,
  /Robert Half/,
  /The Mom Project/,
  /Verticalmove/,
  /Wipro/,

  /Amazon/,
  /Anthropic/,
  /Apple/,
  /^Block$/,
  /Blue Origin/,
  /ByteDance/,
  /Canonical/,
  /Cash App/,
  /EarnIn/,
  /Google DeepMind/,
  /Grindr/,
  /Kohler Ventures/,
  /Knightscope/,
  /LinkedIn/,
  /Lucid Motors/,
  /^Match\b/,
  /Meta/,
  /Microsoft/,
  /Monogram/,
  /Neuralink/,
  /Nextdoor/,
  /OKX/,
  /Perplexity/,
  /Rivian/,
  /Robinhood/,
  /Roblox/,
  /SiriusXM/,
  /SpaceX/,
  /Temu/,
  /Tesla/,
  /TikTok/,
  /Tinder/,
  /Wells Fargo/,
  /^World$/,

  /\w+AI\b/,
  /\bai\b/i,
  /^coin/i,
  /consult/i,
  // /\bgroup\b/i,
  /infote/i,
  /^intelli/i,
  // / llc$/i,
  // /resourc/i,
  // /solutions/i,
  // /staffing/i,
  /^tek/i,
  /tek\b/i,
];

export const isExcludedCompany = company =>
  companyExclusions.some(it => company.match(it));

const titleExclusions = [
  /\bagent/i,
  /\bai\b/i,
  /\banalyst\b/i,
  /\bdirector\b/i,
  /\bintern\b/i,
  /\bjunior\b/i,
  /\blead\b/i,
  /\bmanager\b/i,
  /\bprincipal\b/i,
  /\bqa\b/i,
  /\bresearcher\b/i,
  /\bsecurity\b/i,
  /\btest\b/i,
  /\btester\b/i,
];

export const isExcludedTitle = title =>
  titleExclusions.some(it => title.match(it));
